version: "3.8"

services:
  web_app_nginx :
    image: nginx:alpine
    container_name: "web_app_nginx"
    restart: unless-stopped
    tty: true
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    volumes:
      - ./files/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_docker


networks:
  app_docker:
    driver: bridge